export const USER_AUTH_REQUEST = 'USER_AUTH_REQUEST'
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS'
export const USER_AUTH_FAIL = 'USER_AUTH_FAIL'
export const USER_AUTH_LOGOUT = 'USER_AUTH_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'
export const USER_REGISTER_RESET = 'USER_REGISTER_RESET'

export const GET_OTP_REQUEST = 'GET_OTP_REQUEST'
export const GET_OTP_SUCCESS = 'GET_OTP_SUCCESS'
export const GET_OTP_FAIL = 'GET_OTP_FAIL'
export const GET_OTP_RESET = 'GET_OTP_RESET'

export const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST'
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS'
export const GET_USER_PROFILE_FAIL = 'GET_USER_PROFILE_FAIL'
export const GET_USER_PROFILE_RESET = 'GET_USER_PROFILE_RESET'

export const CREATE_APARTMENT_REQUEST = 'CREATE_APARTMENT_REQUEST'
export const CREATE_APARTMENT_SUCCESS = 'CREATE_APARTMENT_SUCCESS'
export const CREATE_APARTMENT_FAIL = 'CREATE_APARTMENT_FAIL'

export const GET_USER_APARTMENTS_REQUEST = 'GET_USER_APARTMENTS_REQUEST'
export const GET_USER_APARTMENTS_SUCCESS = 'GET_USER_APARTMENTS_SUCCESS'
export const GET_USER_APARTMENTS_FAIL = 'GET_USER_APARTMENTS_FAIL'
export const GET_USER_APARTMENTS_RESET = 'GET_USER_APARTMENTS_RESET'

export const GET_APARTMENT_DETAILS_REQUEST = 'GET_APARTMENT_DETAILS_REQUEST'
export const GET_APARTMENT_DETAILS_SUCCESS = 'GET_APARTMENT_DETAILS_SUCCESS'
export const GET_APARTMENT_DETAILS_FAIL = 'GET_APARTMENT_DETAILS_FAIL'
export const GET_APARTMENT_DETAILS_RESET = 'GET_APARTMENT_DETAILS_RESET'

export const CREATE_BOOKING_REQUEST = 'CREATE_BOOKING_REQUEST'
export const CREATE_BOOKING_SUCCESS = 'CREATE_BOOKING_SUCCESS'
export const CREATE_BOOKING_FAIL = 'CREATE_BOOKING_FAIL'

export const GET_BOOKED_APARTMENTS_REQUEST = 'GET_BOOKED_APARTMENTS_REQUEST'
export const GET_BOOKED_APARTMENTS_SUCCESS = 'GET_BOOKED_APARTMENTS_SUCCESS'
export const GET_BOOKED_APARTMENTS_FAIL = 'GET_BOOKED_APARTMENTS_FAIL'
export const GET_BOOKED_APARTMENTS_RESET = 'GET_BOOKED_APARTMENTS_RESET'
